### PR TITLE
Add entry for DBHub.io

### PR DESCRIPTION
**Pull request by justinclift**
# PR: Thank you!

## Reason

- [x] Add: New Item

## Type

- [x] Database

## Name

DBHub.io

## Link

https://dbhub.io | https://github.com/sqlitebrowser/dbhub.io

## Thank you for improving project

**This helps others find VPS or hosting of their choise**

### CODE REVIEW

**Comment by dalisoft** [comment]
Thank you for contribution @justinclift 

open source field means Is provider gives discounts or free tier for Open Source projects or not. 

And please use No or Yes (see examples), like i am also used yes/no for neon even there was no plans yet

**Comment by dalisoft** [comment]
Please update information based on my above comment so i can approve this and merge. Thank you

**Comment by justinclift** [comment]
Ahhh, understood.  No worries, I'll update it shortly. :smile:

**Comment by justinclift** [comment]
k.  I *think* it's all right now. :smile:

**Comment by dalisoft** [comment]
Thank you @justinclift

**Comment by dalisoft** [comment]
I think it's sub of SQLite and SQLite ORM/clients should work, so i don't think required

**Comment by justinclift** [comment]
No worries. :smile:

**Comment by dalisoft** [comment]
Oh, yep, seems they changed it. You can create PR @justinclift 
Last time i checked they was compatible with SQLite clients

**Comment by justinclift** [comment]
Ahhh ok.  PR coming up. :smile:

**Pull request merged**
